[project]
name = "whatsapp-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rudra Krishna", email = "fallingfish1@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "groq>=1.7.0",
    "langchain-core>=1.6.4",
    "neonize>=0.5.2",
    "python-dotenv>=1.2.3",
]

[project.scripts]
whatsapp-agent = "whatsapp_agent.__main__:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[tool.basedpyright]
include = ["src"]
venvPath = "."
venv = ".venv"
useLibraryCodeForTypes = true
reportMissingTypeStubs = false
reportUnknownMemberType = false
reportUnknownArgumentType = false
reportUnknownVariableType = false
reportUnknownParameterType = false
reportMissingParameterType = false
reportUnusedCallResult = false
reportAny = false
reportExplicitAny = false

